server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  jmx:
    enabled: true
    default_domain: Kafdrop
  jackson:
    deserialization:
      fail_on_unknown_properties: false
      read_unknown_enum_values_as_null: true
  datasource:
    platform: postgres
    url: "${POSTGRES_URL}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driverClassName: org.postgresql.Driver
  ## in case you want to switch authentication from postgresql to mysql
  # datasource:
  #   platform: mysql
  #   url: "${MYSQL_URL}"
  #   username: "${MYSQL_USER}"
  #   password: "${MYSQL_PASSWORD}"
  #   driverClassName: com.mysql.jdbc.Driver

management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: "*"
  server:
    port: 9000

kafdrop.monitor:
  clientId: Kafdrop

kafka:
  brokerConnect: localhost:9092
  isSecured: false
  saslMechanism: "PLAIN"
  securityProtocol: "SASL_PLAINTEXT"
  truststoreFile: "${KAFKA_TRUSTSTORE_FILE:kafka.truststore.jks}"
  propertiesFile : "${KAFKA_PROPERTIES_FILE:kafka.properties}"
  keystoreFile: "${KAFKA_KEYSTORE_FILE:kafka.keystore.jks}"